### ISSUE TITLE
Not able to type ಜ಼ and ಫ಼ in Lipika-IME

### ISSUE THREAD

**Issue by ssnkumar** [ratreya/lipika-ime#55]
Hi,

I am not able to type ಜ಼ and ಫ಼ in Lipika-IME.
In ITRANS, the keys used for typing ಜ಼ is za and ಫ಼ is fa. The same doesn't work in Lipika-IME.
Please let me know, if you are providing a different mapping than that of ITRANS or please fix the issue.

Regards,
Narendra

**Comment by ratreya** [comment]
With [v2.0+](https://github.com/ratreya/lipika-ime/releases/tag/v2.1), you can edit the mapping yourself in LipikaApp and add these entries easily. I am not a big fan of Za and Fa because it is not native to the language and also, it can be created with a combination of ja and nukta and pa and nukta. So, for ಜ಼ you'd type `jaz` and for ಪ಼ you'd type `paz`.
